 // constants/enrollment.ts
export const ENROLLMENT_STEPS = {
  WELCOME: 'welcome',
  PERSONAL_INFO: 'personalInfo', 
  INSTRUCTIONS: 'instructions',
  FACE_CAPTURE: 'faceCapture',
  RETRY_CAPTURE: 'retryCapture',
  REVIEW: 'review',
  SUCCESS: 'success'
} as const;

export const PROGRESS_STEPS = {
  [ENROLLMENT_STEPS.WELCOME]: 0,
  [ENROLLMENT_STEPS.PERSONAL_INFO]: 33,
  [ENROLLMENT_STEPS.INSTRUCTIONS]: 66,
  [ENROLLMENT_STEPS.FACE_CAPTURE]: 66,
  [ENROLLMENT_STEPS.RETRY_CAPTURE]: 66,
  [ENROLLMENT_STEPS.REVIEW]: 100,
  [ENROLLMENT_STEPS.SUCCESS]: 100
};

export const FACE_QUALITY_THRESHOLD = 85;

export const SCAN_SETTINGS = {
  MIN_QUALITY: 80,
  MAX_QUALITY: 100,
  PROGRESS_INTERVAL: 200,
  MIN_PROGRESS_STEP: 5,
  MAX_PROGRESS_STEP: 20
};